### ISSUE TITLE
Package structure for non-`Tool` classes

### ISSUE THREAD

**Issue by tdealtry** [hyperk/hk-LibToolPackTemplate#2]
The way that this template is currently setup is that every folder in the repo is assumed by the `Makefile` to be a `Tool`, with every `.cpp` being compiled the same way (other than `template/` which is explicitly filtered out).

There will certainly be some packages that need some classes that inherit from `Tool`, but others that don't. And it may be that such other classes need a different `g++` command to the `Tool`s. So I'm just opening the question to how we want to set this up in the template, so that there is consistency between packages in how this is done

I see two possible ways to lay this out logically (where here `./` means the root directory of the repo)
1. Tools in `./TOOLNAME`. Other classes in `./src`
1. Tools in `./Tools/TOOLNAME`. Other classes in `./src`

(of course, there may be a better name than `src`)

Thoughts?

**Comment by brichards64** [comment]
are you sure you need a different g++ command? 

seems to me that even entirely non framework related code, could be compiles with the framework -I and -L flags even if they are not needed. The individual include and lib needs of the file can be added to the usertools include and lib paths at the top of the make file and equally be applied and not used in tool compilation

**Comment by tdealtry** [comment]
No idea really. Maybe?

But it's not just the Makefile this effects. Its Import.sh, renameTool.sh, deleteTool.sh, too. And (the most important thing) making it clear for people which classes are tools, and which are not

**Comment by brichards64** [comment]
ok well Tools should be in folders in UserTools.

i believe Import rename and delete works on folders which by above definitions will be tools

**Comment by brichards64** [comment]
If non tool code, is only used internally in a tool it can be added into the Tools folder as a component of the Tool.

otherwise should be in DataModel if used by lots of tools or as an external dependancy.

does that make sense?

**Comment by tdealtry** [comment]
Yeah ok I see with the Tool or with the DataModel makes sense

I still think theres an edge case where a number of tools in the same package need the same code (and putting it in the DataModel is potentially overkill). 

FYI the `UserTools` folder is not used by this template. So perhaps the template needs updating?

**Comment by brichards64** [comment]
your last comment there didnt make sense to me.

after importing an external tool and selecting it with the toolselect script a symlink of the tool folder appears in the UserTools folder like any other non imported tool would Tool.

**Comment by tdealtry** [comment]
I think we're talking about two different things here
- You're talking about how things look when importing into hk-ToolApp which, as you say, will end up in the `UserTools` directory
- I'm talking about how things look in the imported tools' repo (e.g. GHOST-WCSim) that is created from this template (hk-LibToolPackTemplate). This has no such `UserTools` directory

Anyway, I'll close this issue for now, and will reopen it if the edge case I was describing actually becomes a thing
